name: Deploy Gatsby Site to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js (specify your Node version here)
        uses: actions/setup-node@v4
        with:
          node-version: '16' # Use the Node version compatible with your Gatsby version
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build Gatsby Site
        run: npm run build
      
      - name: Install gh-pages Package
        run: npm install gh-pages
      
      - name: Deploy to gh-pages Branch
        run: npx gh-pages -d public

      # This step prints the URL where your site will be published.
      - name: Deployment URL
        run: echo "Your site will be published at https://${{ github.repository_owner }}.github.io/${{ github.repository }}"
